# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIListarAutores.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QStandardItem


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 394)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 631, 301))
        self.tableView.setObjectName("tableView")
        self.btnListar = QtWidgets.QPushButton(self.centralwidget)
        self.btnListar.setGeometry(QtCore.QRect(560, 320, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.btnListar.setFont(font)
        self.btnListar.setObjectName("btnListar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 320, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnFiltrarNacionalidad = QtWidgets.QPushButton(self.centralwidget)
        self.btnFiltrarNacionalidad.setGeometry(QtCore.QRect(470, 320, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.btnFiltrarNacionalidad.setFont(font)
        self.btnFiltrarNacionalidad.setObjectName("btnFiltrarNacionalidad")
        self.txtAutor = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAutor.setGeometry(QtCore.QRect(310, 320, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.txtAutor.setFont(font)
        self.txtAutor.setObjectName("txtAutor")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 320, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(70, 320, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.btnFiltrarEdad = QtWidgets.QPushButton(self.centralwidget)
        self.btnFiltrarEdad.setGeometry(QtCore.QRect(120, 320, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.btnFiltrarEdad.setFont(font)
        self.btnFiltrarEdad.setObjectName("btnFiltrarEdad")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #Poner el servicio
        self.servicioAutor = ServicioAutor()

        #Conectar botones a los metodos
        self.btnListar.clicked.connect(self.listar)
        self.btnFiltrarNacionalidad.clicked.connect(self.filtrarNacionalidad)
        self.btnFiltrarEdad.clicked.connect(self.filtrarEdad)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    

    def listar(self):
        autores = servicioAutor.obtener_autores()

        model = QStandardItemModel()
    
        model.setHorizontalHeaderLabels(["Nombre", "Edad", "Nacionalidad", "Regalias", "Fecha de Nacimiento"])

        for autor in autores:
            row = [
                QStandardItem(autor.nombre),
                QStandardItem(str(autor.edad)),
                QStandardItem(autor.nacionalidad),
                QStandardItem(str(autor.porcentaje_regalias)),
                QStandardItem(autor.fecha_nacimiento.strftime("%Y-%m-%d"))
            ]
            model.appendRow(row)

        self.tableView.setModel(model)

    def filtrarNacionalidad(self):
        autores = servicioAutor.obtener_autores_nacionalidad(self.txtAutor.text())

        model = QStandardItemModel()
        model.setHorizontalHeaderLabels(["Nombre", "Edad", "Nacionalidad", "Regalias", "Fecha de Nacimiento"])

        for autor in autores:
            row = [
                QStandardItem(autor.nombre),
                QStandardItem(str(autor.edad)),
                QStandardItem(autor.nacionalidad),
                QStandardItem(str(autor.porcentaje_regalias)),
                QStandardItem(autor.fecha_nacimiento.strftime("%Y-%m-%d"))
            ]
            model.appendRow(row)

        self.tableView.setModel(model)

    def filtrarEdad(self):
        autores = servicioAutor.obtener_autores_edad(self.spinbox.value())

        model = QStandardItemModel()
        model.setHorizontalHeaderLabels(["Nombre", "Edad", "Nacionalidad", "Regalias", "Fecha de Nacimiento"])

        for autor in autores:
            row = [
                QStandardItem(autor.nombre),
                QStandardItem(str(autor.edad)),
                QStandardItem(autor.nacionalidad),
                QStandardItem(str(autor.porcentaje_regalias)),
                QStandardItem(autor.fecha_nacimiento.strftime("%Y-%m-%d"))
            ]
            model.appendRow(row)

        self.tableView.setModel(model)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Listar autores"))
        self.btnListar.setText(_translate("MainWindow", "Listar"))
        self.label.setText(_translate("MainWindow", "Nacionalidad"))
        self.btnFiltrarNacionalidad.setText(_translate("MainWindow", "Filtrar"))
        self.label_2.setText(_translate("MainWindow", "Edad"))
        self.btnFiltrarEdad.setText(_translate("MainWindow", "Filtrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
